name: Deploy to Cocoapods

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cocoapods # https://cocoapods.org/pods/KhenshinProtocol
    runs-on: macos-latest

    # Only deploy if tests were successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cocoapods
        run: pod install --project-directory=Example

      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
